/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_ihmc_ekf_filter_NativeFilterMatrixOpsWrapper */

#ifndef _Included_us_ihmc_ekf_filter_NativeFilterMatrixOpsWrapper
#define _Included_us_ihmc_ekf_filter_NativeFilterMatrixOpsWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_ihmc_ekf_filter_NativeFilterMatrixOpsWrapper
 * Method:    computeABAt
 * Signature: ([D[D[DII)V
 */
JNIEXPORT void JNICALL Java_us_ihmc_ekf_filter_NativeFilterMatrixOpsWrapper_computeABAt
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
